# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss:

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: darrenFantasy
description: We’re here to put a dent in the universe. Otherwise why else even be here?
links:
  Blog: /archives
  GitHub: https://github.com/darrenfantasy
  Instagram: http://instagram.com/darrenfantasy
  Email: mailto:yuanda.wang1993@gmail.com
  About: /about

# Info
archive_footer_content: stay hungry ,stay foolish .
post_footer_content: I am a slow walker, but I never walk backwards.

duoshuo_shortname: darrenfantasy